PREFIX ex: <http://localhost:7200/andreas-baumann#>
PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>

SELECT ?section WHERE {
  GRAPH <http://localhost:7200/andreas-baumann#> {
    ?farm a was:Farm ;
          was:hasLandSection ?section .
    FILTER(STRSTARTS(STR(?farm), "http://localhost:7200/andreas-baumann#farm-"))
  }
}
