PREFIX ex: <https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-alessandro#>
PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>

SELECT ?section WHERE {
  GRAPH <https://sandbox-graphdb.interactions.ics.unisg.ch/was-exercise-3-alessandro#> {
    ex:farm a was:Farm ;
           was:hasLandSection ?section .
  }
}