PREFIX ex: <http://localhost:7200/andreas-baumann#>
PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?x1 ?y1 ?x2 ?y2 WHERE {
  GRAPH <http://localhost:7200/andreas-baumann#> {
    ex:section1 a was:LandSection ;
                was:hasCoordinates ?coord .
    ?coord was:hasX1 ?x1 ;
           was:hasY1 ?y1 ;
           was:hasX2 ?x2 ;
           was:hasY2 ?y2 .
  }
}
