PREFIX ex: <http://localhost:7200/andreas-baumann#>
PREFIX was: <https://was-course.interactions.ics.unisg.ch/farm-ontology#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?moisture WHERE {
  GRAPH <http://localhost:7200/andreas-baumann#> {
    ex:crop1 a was:Wheat ;
             was:hasMoistureRequirement ?moisture .
  }
}
